<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-04-19 21:37
=======
# Generated by Django 4.1.3 on 2023-04-20 02:25
>>>>>>> 68da2d4b75d92c06d5bf1a66c8833642562cc03a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IAFBenflex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
<<<<<<< HEAD
            options={'ordering': ['username', 'id']},
=======
            options={'ordering': ['id', 'username']},
>>>>>>> 68da2d4b75d92c06d5bf1a66c8833642562cc03a
        ),
    ]
