# Generated by Django 4.1.3 on 2023-04-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IAFBenflex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id', 'username']},
        ),
    ]
