# Generated by Django 4.1.6 on 2023-04-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IAFBenflex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['username', 'id']},
        ),
    ]
